package net.launcher.theme;
public class Message {
    //Логин
    public static String Options = "Настройки";
    public static String Game = "Войти в игру";
    public static String Auth = "Вход";
    public static String Logout = "Выход";
    public static String Back = "Назад";
    public static String Help = "discord";
    public static String Account = "Личный кабинет";
    public static String Personal = "Войти в ЛК";
    public static String Register = "Создать учетную запись";
    public static String Login = "Логин";
    //Регистрация
    public static String closereg = "Отмена";
    public static String register = "Регистрация";
    public static String textloginReg1 = "Ник:";
    public static String textpasswordReg1 = "Пароль:";
    public static String textpassword2Reg1 = "Пароль:";
    public static String textmailReg1 = "E-mail:";
    //Настройки
    public static String options = "Настройки";
    public static String options_close = "Назад";
    public static String loadnews = "Загружать новости";
    public static String Music = "Музыка в лаунчере";
    public static String updatepr = "Принудительное обновление";
    public static String cleanDir = "Очистить папку";
    public static String fullscreen = "Запускать в полном экране";
    public static String memory = "Память (мегабайт):";
    //Личный кабинет
    public static String buyVip = "Купить VIP";
    public static String buyPremium = "Купить Premium";
    public static String buyVipN = "Продлить VIP";
    public static String buyPremiumN = "Продлить Premium";
    public static String buyUnban = "Купить разбан";
    public static String GamePersonal = "В игру";
    public static String buyCloak = "Купить плащ";
    public static String changeSkin = "Сменить скин";
    public static String vaucherButton = "Пополнить";
    public static String buyVaucher = "Купить";
    public static String exchangeButton = "Обменять";
    public static String user = "Игрок";
    public static String vip = "VIP";
    public static String prem = "Premium";
    public static String ban = "Забаненый";
    public static String iconmoney = "%% монет";
    public static String realmoney = "%% рублей";
    public static String exchange = " Монет";
    public static String exchangeTo = "<N/A>";
    public static String vipPrice = "Цена VIP: %% рублей";
    public static String premiumPrice = "Цена Premium: %% рублей";
    public static String unbanPrice = "Цена разбана: %% рублей";
    public static String exchangeRate = "Курс обмена: 1 рубль = %% рублей";
    public static String dateofexpire = "Дата истечения : %%";
    public static String jobname = "Профессия: %%";
    public static String joblvl = "Уровень: %%";
    public static String jobexp = "Опыт: %%";
    //Обновление клиента
    public static String currentfile = "Файл: %%";
    public static String totalsize = "Всего: %% Мбайт";
    public static String currentsize = "Загружено: %% Мбайт";
    public static String downloadspeed = "Скорость: %% кб/сек";
    public static String McDir = "Папка: %%";
    public static String state = "Состояние: %%";
    public static String leftTime = "Осталось: %m минут, %s секунд";
    //Обновление лаунчера
    public static String update = "Требуется обновление";
    public static String str0 = "Для продолжения обновите лаунчер.";
    public static String str1 = "Новая версия содержит улучшения и";
    public static String str2 = "исправления, необходимые для запуска игры.";
    public static String str3 = "";
    public static String str4 = "Нажмите \"Обновить\" для продолжения.";
    public static String str5 = "Нажмите \"Отмена\" для выхода.";
    public static String str6 = "Текущая версия: %%";
    public static String str7 = "Новая версия: %%";
    public static String str8 = "Идет обновление лаунчера...";
    public static String str9 = "Ошибка при обновлении.";
    public static String update_exe = "exe";
    public static String update_jar = "Обновить";
    public static String update_no = "Отмена";
    public static String update_no2 = "Отмена";
    //Ошибка выполнения
    public static String messerr = "Ошибка  выполнения";
    public static String err1 = "Сообщите эту ошибку разработчикам и закройте лаунчер.";
    public static String err2 = "%%";
    //Выполнение
    public static String Loading = "Выполнение...";
    //Сервер
    public static String serveroff = "Оффлайн";
    public static String serverfull = "Сервер переполнен (Всего слотов: %%)";
    public static String serveron = "%% / ##";
    public static String servererr = "Ошибка получения информации";
    //tmpString
    public static String tmpString = "Авторизация...";
    public static String Null = "Ошибка подключения";
    public static String errorTocen = "Ошибка авторизации (Токен устарел)";
    public static String errorLogin = "Ошибка авторизации (Логин, пароль)";
    public static String errorsql = "Ошибка sql";
    public static String client = "Ошибка: %% не найден";
    public static String temp = "Подождите, перед следущей попыткой (Логин Пароль)";
    public static String badhash = "Ошибка: Неподдерживаемый способ хеширования";
    public static String tmpDownload = "Загрузка данных...";
    public static String noactive = "Ваш аккаунт не активирован!";
    public static String skin = "Загрузка скина...";
    public static String cloak = "Загрузка плаща...";
    public static String skinImage = "Парсинг скина...";
    public static String cloakImage = "Парсинг плаща...";
    public static String nofile = "Файл не выбран";
    public static String skinerr = "Этот файл не является файлом скина";
    public static String cloakerr = "Этот файл не является файлом плаща";
    public static String fileerr = "Ошибка загрузки файла!";
    public static String keyerr = "Ключ введен неверно!";
    public static String econo = "Вас нет в базе Fe Economy";
    public static String ecoerr = "Вы не ввели сумму";
    public static String moneyno = "У вас недостаточно средств!";
    public static String done = "Регистрация успешно завершена";
    public static String errorField = "Заполнены не все поля";
    public static String errorMail = "eMail адрес введен некорректно";
    public static String errorMail2 = "eMail адрес содержит запрещенные символы";
    public static String errorLoginSymbol = "Логин содержит запрещенные символы";
    public static String passErrorSymbol = "Пароль содержит запрещенные символы";
    public static String errorPassToPass = "Пароль не совпадает";
    public static String errorSmallLogin = "Логин должен содержать 2-16 символов";
    public static String errorPassSmall = "Пароль должен содержать 6-20 символов";
    public static String emailErrorPovtor = "eMail уже зарегестрирован";
    public static String Errorip = "С вашего ip уже была регистрация";
    public static String loginErrorPovtor = "Пользователем с таким логином уже зарегистрирован";
    public static String registeroff = "Регистрация выключена!";
    public static String unknown = "Неизвестная ошибка (%%)";
    public static String banno = "Вы не забанены";
    public static String serverSelectRowOnline = "%s (%s из %s онлайн)";
    public static String serverSelectRowOffline = "%s (недоступен)";
}
